---
version: '2.2'
services:

  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "8181:80"
    environment:
      - NGINX_PORT=80
    restart: always

volumes:
  open-bank-certs:
    external: true