-- Your SQL goes here
CREATE OR REPLACE FUNCTION maintain_updated_atr()
  RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

create table balancer (
  balance_id int generated by default as identity primary key,
  iban text not null,
  token text not null,
  amount bigint not null default 0,
  type_ text not null,
  lmt bigint not null default -50000,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp);

create trigger balance_updated_at before update
  on balancer for each row execute procedure
  maintain_updated_atr();

insert into balancer (balance_id, iban, token, amount, type_, lmt) values
  (0, 'NL66OPEN0000000000', '00000000000000000000', 100000000000000000, 'AUTO', -50000);

alter table balancer alter column balance_id restart with 1;

create index balancer_iban on balancer using btree (iban);

create table cacr(
  uuid UUID not null primary key,
  iban text,
  token text,
  type_ text,
  reason text,
  created_at timestamp not null default current_timestamp);

create index uuid_cacr on cacr using btree (uuid);

create table cmtr(
  uuid UUID not null primary key,
  reason text,
  created_at timestamp not null default current_timestamp);

create index uuid_cmtr on cmtr using btree (uuid);

